
version: "2"

services:

    logdb:
      image : mariadb
      environment:
        MYSQL_PASSWORD: "pass"
        MYSQL_DATABASE: "minecraft"
        MYSQL_USER: "username"
        MYSQL_ROOT_PASSWORD: "THAT"
      volumes:
        - ./logdb:/var/lib/mysql
      ports:
        - "3306:3306"


    minecraft-server:
      container_name: mc
      image: itzg/minecraft-server
      volumes:
        - "./data:/data"
        - "./LogBlock:/data/plugins/LogBlock"
        - "./LogBlock.jar:/data/plugins/LogBlock.jar"
      ports:
        - "25565:25565"

      environment:
        EULA: "TRUE"
        TYPE: "BUKKIT"
        VERSION : "1.8.8-R0.1-SNAPSHOT-latest"
        DIFFICULTY: "hard"
        MOTD: "188 loggedEnv"
        INIT_MEMORY: "1G"
        MEMORY : "3G"
        ONLINE_MODE : "FALSE"

      tty: false
      stdin_open: false
